Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "D:\anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fixedpt(lambda x: x-(x**2-2)/4, -5, 1e-5, 15)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mOverflowError[0m                             Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_7728/3645725987.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mfixedpt[0m[1;33m([0m[1;32mlambda[0m [0mx[0m[1;33m:[0m [0mx[0m[1;33m-[0m[1;33m([0m[0mx[0m[1;33m**[0m[1;36m2[0m[1;33m-[0m[1;36m2[0m[1;33m)[0m[1;33m/[0m[1;36m4[0m[1;33m,[0m [1;33m-[0m[1;36m5[0m[1;33m,[0m [1;36m1e-5[0m[1;33m,[0m [1;36m15[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\AppData\Local\Temp/ipykernel_7728/689667504.py[0m in [0;36mfixedpt[1;34m(g, pzero, eps, N)[0m
[0;32m      4[0m     [1;32mwhile[0m [0mn[0m[1;33m<[0m[0mN[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m         [0mprint[0m[1;33m([0m[0mn[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 6[1;33m         [0mpone[0m [1;33m=[0m [0mg[0m[1;33m([0m[0mpzero[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      7[0m         [1;32mif[0m [0mnp[0m[1;33m.[0m[0mabs[0m[1;33m([0m[0mpone[0m[1;33m-[0m[0mpzero[0m[1;33m)[0m[1;33m<[0m[0meps[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m             [0mprint[0m[1;33m([0m[1;34m'p is '[0m[1;33m,[0m [0mpone[0m[1;33m,[0m [1;34m' and the iteration number is '[0m[1;33m,[0m [0mn[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Temp/ipykernel_7728/3645725987.py[0m in [0;36m<lambda>[1;34m(x)[0m
[1;32m----> 1[1;33m [0mfixedpt[0m[1;33m([0m[1;32mlambda[0m [0mx[0m[1;33m:[0m [0mx[0m[1;33m-[0m[1;33m([0m[0mx[0m[1;33m**[0m[1;36m2[0m[1;33m-[0m[1;36m2[0m[1;33m)[0m[1;33m/[0m[1;36m4[0m[1;33m,[0m [1;33m-[0m[1;36m5[0m[1;33m,[0m [1;36m1e-5[0m[1;33m,[0m [1;36m15[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mOverflowError[0m: (34, 'Result too large')
OverflowError: (34, 'Result too large')

