Traceback (most recent call last):
  File "C:\Users\yanin\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\yanin\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\yanin\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\yanin\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\yanin\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\yanin\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\yanin\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\yanin\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for n in range(1, 1001):
    print(n, f(n))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mOverflowError[0m                             Traceback (most recent call last)
Cell [1;32mIn[7], line 2[0m
[0;32m      1[0m [38;5;28;01mfor[39;00m n [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m1[39m, [38;5;241m1001[39m):
[1;32m----> 2[0m     [38;5;28mprint[39m(n, [43mf[49m[43m([49m[43mn[49m[43m)[49m)

Cell [1;32mIn[6], line 2[0m, in [0;36m<lambda>[1;34m(n)[0m
[0;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mspecial[39;00m [38;5;28;01mimport[39;00m factorial
[1;32m----> 2[0m f [38;5;241m=[39m [38;5;28;01mlambda[39;00m n: [43mn[49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mn[49m[38;5;241;43m/[39;49m[43mfactorial[49m[43m([49m[43mn[49m[43m)[49m

[1;31mOverflowError[0m: int too large to convert to float
OverflowError: int too large to convert to float

